# Generated by Django 5.0.6 on 2024-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
