# Generated by Django 5.0.6 on 2024-06-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_department_alter_student_guardian_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='start_time',
            new_name='leave_time',
        ),
    ]
